from pathlib import Path
import sys,re,json
root=Path(sys.argv[1] if len(sys.argv)>1 else '.')

# storage migration
p=root/'js/storage.js'; s=p.read_text(encoding='utf-8')
s=s.replace('version: 73,','version: 74,')
s=s.replace('settings: {notifications:true},','settings: {notifications:true},\n      users: [{id:"owner",name:"Yönetici",role:"Yönetici",pinHash:"",active:true,createdAt:new Date().toISOString()}],\n      activeUserId: "owner",\n      attachments: [],\n      cloudMeta: {lastPush:null,lastPull:null,dirty:false,deviceId:"dev-"+Math.random().toString(36).slice(2,10)},')
s=s.replace('state.settings ||= {notifications:true};','state.settings ||= {notifications:true};\n      state.users ||= [{id:"owner",name:state.company?.manager||"Yönetici",role:"Yönetici",pinHash:"",active:true,createdAt:new Date().toISOString()}];\n      state.activeUserId ||= state.users[0]?.id||"owner";\n      state.attachments ||= [];\n      state.cloudMeta ||= {lastPush:null,lastPull:null,dirty:false,deviceId:"dev-"+Math.random().toString(36).slice(2,10)};')
s=s.replace('localStorage.setItem(window.OZ_CONFIG.storageKey, JSON.stringify(state));','state.cloudMeta ||= {};\n    state.cloudMeta.dirty = true;\n    localStorage.setItem(window.OZ_CONFIG.storageKey, JSON.stringify(state));')
p.write_text(s,encoding='utf-8')

# index navigation + screens
p=root/'index.html'; h=p.read_text(encoding='utf-8')
h=h.replace('<button class="nav-btn" data-view="quality"><span>✓</span> Eksik Veri <b id="qualityBadge" class="nav-badge">0</b></button>', '<button class="nav-btn" data-view="quality"><span>✓</span> Eksik Veri <b id="qualityBadge" class="nav-badge">0</b></button>\n        <button class="nav-btn" data-view="users"><span>♟</span> Kullanıcı & Yetki</button>')
h=h.replace('<button class="nav-btn" data-view="profitability"><span>₺</span> Hayvan Kârlılığı</button>', '<button class="nav-btn" data-view="profitability"><span>₺</span> Hayvan Kârlılığı</button>\n        <button class="nav-btn" data-view="herdPerformance"><span>▥</span> Sürü Performansı</button>\n        <button class="nav-btn" data-view="qr"><span>⌗</span> Hayvan QR</button>\n        <button class="nav-btn" data-view="attachments"><span>▧</span> Belge / Fotoğraf</button>')
h=h.replace('<button class="nav-btn" data-view="backup"><span>⇅</span> Yedek / Aktarım</button>', '<button class="nav-btn" data-view="backup"><span>⇅</span> Yedek / Aktarım</button>\n        <button class="nav-btn" data-view="cloud"><span>☁</span> Bulut Senkron</button>')
center='''        <article class="panel v74-centers-panel"><div class="panel-head"><div><span class="eyebrow">V7.4 ŞİRKET ALTYAPISI</span><h2>Yetki, Belge, QR, Sürü ve Bulut</h2></div></div><div class="quick-entry-grid"><button class="quick-entry-card" data-go="users"><span class="quick-icon">♟</span><span><strong>Kullanıcılar</strong><small>Rol & yetki</small></span></button><button class="quick-entry-card" data-go="attachments"><span class="quick-icon">▧</span><span><strong>Belgeler</strong><small>Fotoğraf / PDF</small></span></button><button class="quick-entry-card" data-go="qr"><span class="quick-icon">⌗</span><span><strong>Hayvan QR</strong><small>Üret / okut</small></span></button><button class="quick-entry-card" data-go="herdPerformance"><span class="quick-icon">▥</span><span><strong>Sürü Performansı</strong><small>30 günlük skor</small></span></button><button class="quick-entry-card" data-go="cloud"><span class="quick-icon">☁</span><span><strong>Bulut</strong><small>Yerel-first senkron</small></span></button></div></article>\n\n'''
h=h.replace('        <article class="panel quick-lists-panel">',center+'        <article class="panel quick-lists-panel">')
h=h.replace('''        <article class="panel"><div class="panel-head"><div><span class="eyebrow">ÜRETİM</span><h2>Hayvan Bazlı Süt Kayıtları</h2></div><button id="animalAddMilkBtn" class="secondary-btn">+ Süt Kaydı</button></div><div id="animalMilkHistory" class="business-list"></div></article>''','''        <article class="panel"><div class="panel-head"><div><span class="eyebrow">ÜRETİM</span><h2>Hayvan Bazlı Süt Kayıtları</h2></div><button id="animalAddMilkBtn" class="secondary-btn">+ Süt Kaydı</button></div><div id="animalMilkHistory" class="business-list"></div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">DOSYALAR</span><h2>Fotoğraf & Belgeler</h2></div><button id="animalAddAttachmentBtn" class="secondary-btn">+ Belge / Fotoğraf</button></div><div id="animalAttachmentList" class="attachment-grid"></div></article>''')
sections='''
      <section id="usersView" class="view"><div class="page-head"><div><span class="eyebrow">ERİŞİM KONTROLÜ</span><h1>Kullanıcı & Yetki Merkezi</h1><p>Yönetici, muhasebe, çalışan, veteriner ve gözlemci rolleri.</p></div><div class="head-actions"><button id="switchUserBtn" class="secondary-btn">Kullanıcı Değiştir</button><button id="newUserBtn" class="primary-btn">+ Kullanıcı</button></div></div><div id="userStats" class="mini-kpi-grid"></div><div class="dashboard-grid"><article class="panel"><div class="panel-head"><h2>Kullanıcılar</h2></div><div id="userList" class="stack"></div></article><article class="panel"><div class="panel-head"><h2>Rol Yetkileri</h2></div><div id="roleMatrix" class="stack"></div></article></div><div class="security-note v74-security"><strong>Yerel güvenlik sınırı</strong><span>Bu APK'daki rol kontrolleri cihaz içinde uygulanır. Bulut sunucusu bağlandığında aynı yetkilerin sunucu tarafında da zorlanması gerekir.</span></div></section>
      <section id="attachmentsView" class="view"><div class="page-head"><div><span class="eyebrow">DİJİTAL DOSYA</span><h1>Belge & Fotoğraf Merkezi</h1><p>Hayvan fotoğrafı, reçete, fatura ve diğer belgeleri kayda bağla.</p></div><button id="newAttachmentBtn" class="primary-btn">+ Dosya Ekle</button></div><div id="attachmentStats" class="mini-kpi-grid"></div><article class="panel"><div class="panel-head"><h2>Dosyalar</h2><select id="attachmentFilter" style="max-width:180px"><option value="all">Tümü</option><option value="animals">Hayvan</option><option value="health">Sağlık</option><option value="finance">Finans</option><option value="purchase">Satın Alma</option><option value="general">Genel</option></select></div><div id="attachmentList" class="attachment-grid"></div></article></section>
      <section id="qrView" class="view"><div class="page-head"><div><span class="eyebrow">HIZLI HAYVAN ERİŞİMİ</span><h1>Hayvan QR Merkezi</h1><p>Küpeye özel QR üret; kamerayla okutunca hayvan profiline git.</p></div><button id="scanQrBtn" class="primary-btn">▣ QR Tara</button></div><div class="dashboard-grid"><article class="panel"><label class="field-label">Hayvan<select id="qrAnimalSelect"></select></label><div id="qrAnimalSummary" class="qr-animal-summary"></div></article><article class="panel qr-card"><div id="qrImageWrap" class="qr-image-wrap"><div class="empty">Hayvan seç.</div></div><div class="qr-actions"><button id="refreshQrBtn" class="secondary-btn">QR Yenile</button><button id="openQrAnimalBtn" class="primary-btn">Profili Aç</button></div></article></div></section>
      <section id="herdPerformanceView" class="view"><div class="page-head"><div><span class="eyebrow">SÜRÜ ANALİTİĞİ</span><h1>Gelişmiş Sürü Performansı</h1><p>30 günlük hayvan-bazlı süt, sağlık ve veri kalitesinden performans görünümü.</p></div></div><div id="herdPerformanceStats" class="mini-kpi-grid"></div><article class="panel"><div class="panel-head"><h2>Hayvan Sıralaması</h2><span class="muted-text">En az 3 hayvan-bazlı süt kaydı olanlarda skor hesaplanır.</span></div><div id="herdPerformanceList" class="stack"></div></article></section>
      <section id="cloudView" class="view"><div class="page-head"><div><span class="eyebrow">LOCAL-FIRST</span><h1>Bulut Senkronizasyonu</h1><p>Cihaz verisini ÖZBİLTAR Cloud Bridge sunucusuna gönder veya sunucudan geri al.</p></div></div><div id="cloudStats" class="mini-kpi-grid"></div><div class="dashboard-grid"><article class="panel"><div class="panel-head"><h2>Bağlantı</h2></div><div class="settings-list"><label class="field-label">Sunucu URL<input id="cloudUrl" inputmode="url" placeholder="https://.../api"></label><label class="field-label">Erişim Anahtarı<input id="cloudToken" type="password" autocomplete="off"></label><label class="field-label">Cihaz Adı<input id="cloudDevice" placeholder="Çiftlik Telefonu"></label><label class="toggle-row"><input id="cloudAuto" type="checkbox"> Otomatik gönderim</label><button id="saveCloudBtn" class="secondary-btn">Bağlantıyı Kaydet</button></div></article><article class="panel"><div class="panel-head"><h2>Senkron</h2></div><div id="cloudStatusBox" class="cloud-status-box"></div><div class="cloud-actions"><button id="cloudPushBtn" class="primary-btn">↑ Buluta Gönder</button><button id="cloudPullBtn" class="secondary-btn">↓ Buluttan Al</button><button id="cloudTestBtn" class="secondary-btn">Bağlantıyı Test Et</button></div></article></div><div class="security-note"><strong>Gerçek bulut için sunucu gerekir</strong><span>APK içinde bulut istemcisi hazırdır. Kaynak paketindeki cloud-server servisinin internette yayınlanması ve URL/anahtarın buraya girilmesi gerekir.</span></div></section>
'''
h=h.replace('<section id="reportsView" class="view">',sections+'<section id="reportsView" class="view">')
h=h.replace('<script src="./js/v73.js"></script>\n<script src="./js/app.js"></script>','<script src="./js/v73.js"></script>\n<script src="./js/v74.js"></script>\n<script src="./js/app.js"></script>\n<script src="./js/v74-ui.js"></script>')
p.write_text(h,encoding='utf-8')

# app integration
p=root/'js/app.js'; a=p.read_text(encoding='utf-8')
a=a.replace('  function switchView(name){\n    document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));','  function switchView(name){\n    if(window.OZ_V74_UI && !window.OZ_V74_UI.canView(name)){ toast("Bu bölüm için yetkin yok."); return; }\n    document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));')
a=a.replace('    if(name==="monthlyClose") renderMonthlyClose();\n  }','    if(name==="monthlyClose") renderMonthlyClose();\n    if(window.OZ_V74_UI) window.OZ_V74_UI.render(name);\n  }',1)
a=a.replace('      STORE.save(state,event);\n      renderAll();','      STORE.save(state,event);\n      if(window.OZ_V74_UI) window.OZ_V74_UI.afterSave(event);\n      renderAll();')
a=a.replace('  function renderSettings(){\n    $("profileName").textContent=state.company.manager||"Yönetici";','  function renderSettings(){\n    const au=window.OZ_V74?window.OZ_V74.activeUser(state):null;\n    $("profileName").textContent=au?.name||state.company.manager||"Yönetici";\n    $("profileRole").textContent=au?(window.OZ_V74.roles[au.role]?.label||au.role):"Tam Yetki";')
a=a.replace('  if("serviceWorker" in navigator){','''  window.OZ_APP_V74={getState:()=>state,replaceState:s=>{state=s;renderAll();if(window.OZ_V74_UI)window.OZ_V74_UI.renderCurrent();},save,switchView,toast,openModal,closeModal,formActions,renderAll,getCurrentModule:()=>currentModule,getSelectedListModule:()=>selectedListModule,getCurrentAnimalId:()=>currentAnimalId,openAnimalByEarTag:ear=>{const x=state.data.animals.find(v=>String(v.earTag)===String(ear));if(!x){toast("Bu küpe sürü listesinde yok.");return false;}currentAnimalId=x.id;renderAnimalProfile();switchView("animalProfile");return true;}};

  if("serviceWorker" in navigator){''')
p.write_text(a,encoding='utf-8')

# Android
p=root/'android-native/app/build.gradle'; g=p.read_text(encoding='utf-8').replace('versionCode 73','versionCode 74').replace('versionName "7.3.0"','versionName "7.4.0"')
if 'zxing-android-embedded' not in g:g=g.replace('dependencies {\n}', 'dependencies {\n    implementation "com.journeyapps:zxing-android-embedded:4.3.0"\n    implementation "com.google.zxing:core:3.5.3"\n}')
p.write_text(g,encoding='utf-8')
p=root/'android-native/app/src/main/AndroidManifest.xml'; m=p.read_text(encoding='utf-8')
if 'android.permission.CAMERA' not in m:m=m.replace('<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>','<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n    <uses-permission android:name="android.permission.CAMERA"/>')
p.write_text(m,encoding='utf-8')

p=root/'android-native/app/src/main/java/com/ozbiltar/yonetim/MainActivity.java'; j=p.read_text(encoding='utf-8')
if 'IntentIntegrator' not in j:
    j=j.replace('import java.nio.charset.StandardCharsets;','''import java.nio.charset.StandardCharsets;\nimport java.io.ByteArrayOutputStream;\nimport android.graphics.Bitmap;\nimport android.graphics.Color;\nimport android.util.Base64;\nimport com.google.zxing.BarcodeFormat;\nimport com.google.zxing.common.BitMatrix;\nimport com.google.zxing.qrcode.QRCodeWriter;\nimport com.journeyapps.barcodescanner.IntentIntegrator;\nimport com.journeyapps.barcodescanner.IntentResult;\nimport org.json.JSONObject;''')
    j=j.replace('''    protected void onActivityResult(int requestCode, int resultCode, Intent data) {\n        super.onActivityResult(requestCode, resultCode, data);''','''    protected void onActivityResult(int requestCode, int resultCode, Intent data) {\n        IntentResult qrResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);\n        if (qrResult != null && qrResult.getContents() != null) {\n            final String code = qrResult.getContents();\n            webView.post(() -> webView.evaluateJavascript("window.OZ_V74_UI && window.OZ_V74_UI.onQrScanned(" + JSONObject.quote(code) + ")", null));\n            return;\n        }\n        super.onActivityResult(requestCode, resultCode, data);''')
    needle='''        @JavascriptInterface\n        public void saveTextFile(final String filename, final String content, final String mime) {'''
    methods='''        @JavascriptInterface\n        public void scanQr() { runOnUiThread(() -> { IntentIntegrator integrator = new IntentIntegrator(MainActivity.this); integrator.setPrompt("ÖZBİLTAR hayvan QR kodunu okutun"); integrator.setBeepEnabled(false); integrator.setOrientationLocked(false); integrator.initiateScan(); }); }\n\n        @JavascriptInterface\n        public String generateQr(final String text, final int requestedSize) { try { int size=Math.max(220,Math.min(900,requestedSize)); BitMatrix matrix=new QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,size,size); Bitmap bmp=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888); for(int x=0;x<size;x++)for(int y=0;y<size;y++)bmp.setPixel(x,y,matrix.get(x,y)?Color.BLACK:Color.WHITE); ByteArrayOutputStream out=new ByteArrayOutputStream(); bmp.compress(Bitmap.CompressFormat.PNG,100,out); return "data:image/png;base64,"+Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP); } catch(Exception e){e.printStackTrace();return "";} }\n\n'''+needle
    j=j.replace(needle,methods)
p.write_text(j,encoding='utf-8')

# versions
p=root/'js/config.js'; x=p.read_text(encoding='utf-8').replace('version: "7.3.0"','version: "7.4.0"');p.write_text(x,encoding='utf-8')
p=root/'package.json'; q=json.loads(p.read_text(encoding='utf-8'));q['version']='7.4.0';q['name']='ozbiltar-yonetim-ai-pro-v7-4';p.write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf-8')
p=root/'manifest.webmanifest'; q=json.loads(p.read_text(encoding='utf-8'));q['name']='ÖZBİLTAR Yönetim AI Pro V7.4';q['description']='ÖZBİLTAR profesyonel şirket, sürü, belge, QR, yetki ve bulut yönetimi';p.write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf-8')
p=root/'sw.js'; sw=p.read_text(encoding='utf-8').replace('ozbiltar-pro-v7.3','ozbiltar-pro-v74').replace('ozbiltar-pro-v73','ozbiltar-pro-v74')
if './js/v74.js' not in sw: sw=sw.replace('"./js/v73.js",','"./js/v73.js",\n  "./js/v74.js",\n  "./js/v74-ui.js",')
p.write_text(sw,encoding='utf-8')
print('V7.4 patch applied')