(()=>{
  const V=window.OZ_V74, A=()=>window.OZ_APP_V74, $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const money=v=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(v)||0);
  const state=()=>A().getState();
  const user=()=>V.activeUser(state());
  const canView=view=>V.canView(state(),view);
  const canWriteModule=m=>V.canWriteModule(state(),m);
  function renderCurrent(){const active=document.querySelector('.view.active');if(active)render(active.id.replace(/View$/,''));}
  function updateHeader(){const u=user();if($("profileName"))$("profileName").textContent=u.name;if($("profileRole"))$("profileRole").textContent=V.roles[u.role]?.label||u.role;document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('permission-hidden',!canView(b.dataset.view)));}
  function roleLine(role){const r=V.roles[role];return `<div class="role-row"><div><strong>${esc(role)}</strong><small>${esc(r.label)}</small></div><div>${r.views==='*'?'Tüm ekranlar':r.views.length+' ekran'} · ${r.write==='*'?'Tüm kayıtlar':r.write.length+' yazma yetkisi'}</div></div>`}
  function renderUsers(){const s=state(),u=user();$("userStats").innerHTML=[["Aktif Kullanıcı",u.name],["Rol",u.role],["Kullanıcı",s.users.length],["PIN'li",s.users.filter(x=>x.pinHash).length]].map(x=>`<div class="mini-kpi"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('');$("userList").innerHTML=s.users.map(x=>`<div class="user-row ${x.id===u.id?'selected':''}"><div><div class="row-title">${esc(x.name)}</div><div class="muted-text">${esc(x.role)} · ${x.pinHash?'PIN aktif':'PIN yok'} ${x.active===false?'· PASİF':''}</div></div><div class="business-list-actions"><button class="action-btn switch-user-inline" data-id="${x.id}">Geç</button>${u.role==='Yönetici'&&x.id!=='owner'?`<button class="action-btn toggle-user" data-id="${x.id}">${x.active===false?'Aktifleştir':'Pasifleştir'}</button>`:''}</div></div>`).join('');$("roleMatrix").innerHTML=Object.keys(V.roles).map(roleLine).join('');document.querySelectorAll('.switch-user-inline').forEach(b=>b.onclick=()=>switchUser(b.dataset.id));document.querySelectorAll('.toggle-user').forEach(b=>b.onclick=()=>{const x=s.users.find(v=>v.id===b.dataset.id);x.active=x.active===false?true:false;A().save('Kullanıcı durumu güncellendi');renderUsers();});}
  async function switchUser(id){const s=state(),target=s.users.find(x=>x.id===id&&x.active!==false);if(!target){A().toast('Kullanıcı aktif değil.');return}if(target.pinHash){const pin=prompt(`${target.name} PIN:`);if(pin===null)return;const hash=await V.pinHash(pin);if(hash!==target.pinHash){alert('PIN yanlış.');return}}s.activeUserId=target.id;A().save('Aktif kullanıcı değiştirildi');updateHeader();A().switchView('dashboard');A().toast(`${target.name} olarak geçildi`);}
  function openNewUser(){if(user().role!=='Yönetici'){A().toast('Yalnız yönetici kullanıcı ekleyebilir.');return}A().openModal('Yeni Kullanıcı',`<label class="wide">Ad Soyad<input name="name" required></label><label>Rol<select name="role">${Object.keys(V.roles).map(r=>`<option>${r}</option>`).join('')}</select></label><label>PIN (4-6 rakam)<input name="pin" inputmode="numeric" pattern="[0-9]{4,6}" required></label>${A().formActions()}`,async e=>{e.preventDefault();const f=new FormData(e.target),pin=String(f.get('pin')||'');if(!/^\d{4,6}$/.test(pin)){alert('PIN 4-6 rakam olmalı.');return}state().users.push({id:'u-'+Date.now().toString(36),name:f.get('name'),role:f.get('role'),pinHash:await V.pinHash(pin),active:true,createdAt:new Date().toISOString()});A().closeModal();A().save('Yeni kullanıcı eklendi');renderUsers();});document.querySelector('.cancel-modal').onclick=A().closeModal;}

  async function fileToData(file){if(!file)return null;if(file.size>8*1024*1024)throw new Error('Dosya 8 MB üstünde.');if(file.type.startsWith('image/')){const url=URL.createObjectURL(file);const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=url});let w=img.width,h=img.height,scale=Math.min(1,1600/Math.max(w,h));w=Math.round(w*scale);h=Math.round(h*scale);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);return c.toDataURL('image/jpeg',.78)}return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
  function attachmentCard(x){const thumb=x.mime?.startsWith('image/')?`<img src="${x.dataUrl}" alt="">`:`<div class="doc-icon">PDF</div>`;return `<article class="attachment-card"><div class="attachment-thumb">${thumb}</div><div class="attachment-copy"><strong>${esc(x.name)}</strong><small>${esc(x.entityType||'general')} · ${esc(x.entityKey||'Genel')}</small><em>${new Date(x.createdAt).toLocaleDateString('tr-TR')} · ${esc(x.createdBy||'')}</em></div><div class="attachment-actions"><a class="action-btn" href="${x.dataUrl}" target="_blank">Aç</a>${user().role==='Yönetici'||canWriteModule(x.entityType)?`<button class="action-btn delete-attachment" data-id="${x.id}">Sil</button>`:''}</div></article>`}
  function bindAttachmentDelete(){document.querySelectorAll('.delete-attachment').forEach(b=>b.onclick=()=>{if(!confirm('Dosya silinsin mi?'))return;const s=state();s.attachments=s.attachments.filter(x=>x.id!==b.dataset.id);A().save('Belge/fotoğraf silindi');renderAttachments();renderAnimalAttachments();})}
  function renderAttachments(){const s=state(),filter=$("attachmentFilter")?.value||'all',rows=s.attachments.filter(x=>filter==='all'||x.entityType===filter);$("attachmentStats").innerHTML=[["Toplam",s.attachments.length],["Fotoğraf",s.attachments.filter(x=>x.mime?.startsWith('image/')).length],["PDF/Belge",s.attachments.filter(x=>!x.mime?.startsWith('image/')).length],["Hayvana Bağlı",s.attachments.filter(x=>x.entityType==='animals').length]].map(x=>`<div class="mini-kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$("attachmentList").innerHTML=rows.length?rows.slice().reverse().map(attachmentCard).join(''):'<div class="empty">Dosya yok.</div>';bindAttachmentDelete();}
  function openAttachmentModal(preset={}){const moduleOpts=[['general','Genel'],...Object.entries(window.OZ_SCHEMAS).map(([k,v])=>[k,v.name])];A().openModal('Belge / Fotoğraf Ekle',`<label>Bağlı Birim<select name="entityType">${moduleOpts.map(x=>`<option value="${x[0]}" ${preset.entityType===x[0]?'selected':''}>${esc(x[1])}</option>`).join('')}</select></label><label>İlişki / Küpe / Kod<input name="entityKey" value="${esc(preset.entityKey||'')}"></label><label class="wide">Dosya<input type="file" name="file" accept="image/*,application/pdf" required></label><label class="wide">Not<input name="note"></label>${A().formActions()}`,async e=>{e.preventDefault();const f=new FormData(e.target),file=f.get('file');try{A().toast('Dosya hazırlanıyor...');const dataUrl=await fileToData(file);if(dataUrl.length>3_500_000){alert('Dosya sıkıştırıldıktan sonra hâlâ büyük. Daha küçük dosya seç.');return}state().attachments.push({id:'att-'+Date.now().toString(36),name:file.name,mime:file.type||'application/octet-stream',dataUrl,entityType:f.get('entityType'),entityKey:f.get('entityKey'),note:f.get('note'),createdAt:new Date().toISOString(),createdBy:user().name});A().closeModal();A().save('Belge/fotoğraf eklendi');renderAttachments();renderAnimalAttachments();A().toast('Dosya kaydedildi ✓')}catch(err){alert(err.message||'Dosya okunamadı.')}});document.querySelector('.cancel-modal').onclick=A().closeModal;}
  function renderAnimalAttachments(){if(!$("animalAttachmentList"))return;const s=state(),id=A().getCurrentAnimalId(),a=s.data.animals.find(x=>x.id===id);if(!a){$("animalAttachmentList").innerHTML='';return}const rows=s.attachments.filter(x=>x.entityType==='animals'&&String(x.entityKey)===String(a.earTag));$("animalAttachmentList").innerHTML=rows.length?rows.slice().reverse().map(attachmentCard).join(''):'<div class="empty">Bu hayvana bağlı fotoğraf/belge yok.</div>';bindAttachmentDelete();}

  function renderQr(){const s=state(),sel=$("qrAnimalSelect");if(!sel)return;const current=sel.value;sel.innerHTML=s.data.animals.filter(a=>!["Satıldı","Öldü"].includes(a.status)).map(a=>`<option value="${esc(a.earTag)}">Küpe ${esc(a.earTag)}${a.alias||a.name?' · '+esc(a.alias||a.name):''}</option>`).join('');if(current&&[...sel.options].some(o=>o.value===current))sel.value=current;const ear=sel.value,a=s.data.animals.find(x=>String(x.earTag)===String(ear));$("qrAnimalSummary").innerHTML=a?`<div class="profile-info-grid"><div class="profile-info-item"><span>Küpe</span><strong>${esc(a.earTag)}</strong></div><div class="profile-info-item"><span>Durum</span><strong>${esc(a.status||'—')}</strong></div><div class="profile-info-item"><span>Irk</span><strong>${esc(a.breed||'—')}</strong></div><div class="profile-info-item"><span>Lakap</span><strong>${esc(a.alias||a.name||'—')}</strong></div></div>`:'<div class="empty">Hayvan yok.</div>';const text=ear?`OZBILTAR:ANIMAL:${ear}`:'';let data='';if(text&&window.AndroidBridge&&typeof AndroidBridge.generateQr==='function'){try{data=AndroidBridge.generateQr(text,520)||''}catch{}}$("qrImageWrap").innerHTML=data?`<img src="${data}" alt="Hayvan QR"><small>${esc(text)}</small>`:`<div class="empty">QR üretimi Android APK içinde kullanılabilir.</div>`;}
  function onQrScanned(text){if(!text)return;const m=String(text).match(/^OZBILTAR:ANIMAL:(.+)$/);if(!m){alert('Bu QR ÖZBİLTAR hayvan kodu değil.');return}A().openAnimalByEarTag(m[1]);}

  function renderHerd(){const x=V.herdPerformance(state());$("herdPerformanceStats").innerHTML=[["Aktif Hayvan",x.total],["Skorlanabilen",x.known],["Veri Kapsama",'%'+x.coverage],["Sürü Ort. Süt",x.herdAvg?x.herdAvg.toFixed(1)+' L/kayıt':'—']].map(v=>`<div class="mini-kpi"><span>${v[0]}</span><strong>${v[1]}</strong></div>`).join('');$("herdPerformanceList").innerHTML=x.rows.length?x.rows.map(r=>`<div class="herd-row ${r.score===null?'uncertain':''}" data-ear="${esc(r.animal.earTag)}"><div class="row-top"><div><div class="row-title">Küpe ${esc(r.animal.earTag)} ${r.animal.alias||r.animal.name?'· '+esc(r.animal.alias||r.animal.name):''}</div><div class="muted-text">${esc(r.animal.status||'—')} · 30 gün ${r.count} süt kaydı · ${r.health} sağlık kaydı</div></div><span class="score-badge ${r.score===null?'amber':r.score>=75?'green':r.score>=55?'blue':'red'}">${r.score===null?'VERİ YETERSİZ':r.score+'/100'}</span></div><div class="herd-metrics"><div><span>Ort. Süt</span><b>${r.count?r.avg.toFixed(1)+' L':'—'}</b></div><div><span>Trend</span><b>${r.trend===null?'—':(r.trend>=0?'+':'')+r.trend.toFixed(1)+'%'}</b></div><div><span>Profil</span><b>%${r.quality}</b></div><div><span>Sağlık 90g</span><b>${r.health}</b></div></div><button class="action-btn open-herd-animal" data-ear="${esc(r.animal.earTag)}">Profili Aç</button></div>`).join(''):'<div class="empty">Aktif hayvan yok.</div>';document.querySelectorAll('.open-herd-animal').forEach(b=>b.onclick=()=>A().openAnimalByEarTag(b.dataset.ear));}

  function cloudEndpoint(c,path=''){return String(c.url||'').replace(/\/$/,'')+path}
  function cloudHeaders(c){return {'Content-Type':'application/json','Authorization':'Bearer '+(c.token||''),'X-OZBILTAR-Device':state().cloudMeta.deviceId||''}}
  function renderCloud(){const c=V.cloudConfig(),m=state().cloudMeta||{};$("cloudUrl").value=c.url||'';$("cloudToken").value=c.token||'';$("cloudDevice").value=c.device||'';$("cloudAuto").checked=!!c.auto;$("cloudStats").innerHTML=[["Durum",c.url?'Yapılandırıldı':'Bağlı değil'],["Son Gönderim",m.lastPush?new Date(m.lastPush).toLocaleString('tr-TR'):'—'],["Son Alım",m.lastPull?new Date(m.lastPull).toLocaleString('tr-TR'):'—'],["Yerel Değişiklik",m.dirty?'Var':'Yok']].map(v=>`<div class="mini-kpi"><span>${v[0]}</span><strong>${esc(v[1])}</strong></div>`).join('');$("cloudStatusBox").innerHTML=c.url?`<strong>${esc(c.device||'Bu cihaz')}</strong><span>${esc(c.url)}</span><small>Veri yalnız sen “Gönder” dediğinde veya otomatik gönderim açıksa sunucuya çıkar.</small>`:'<div class="empty">Sunucu URL ve erişim anahtarı girilmedi.</div>';}
  function saveCloud(){const url=$("cloudUrl").value.trim();if(url&&!/^https:\/\//i.test(url)){alert('Bulut URL https:// ile başlamalı.');return}V.saveCloudConfig({url,token:$("cloudToken").value.trim(),device:$("cloudDevice").value.trim()||'ÖZBİLTAR Android',auto:$("cloudAuto").checked});renderCloud();A().toast('Bulut ayarları kaydedildi');}
  async function testCloud(){const c=V.cloudConfig();if(!c.url){A().toast('Önce sunucu URL gir.');return}try{const r=await fetch(cloudEndpoint(c,'/health'),{headers:cloudHeaders(c)});if(!r.ok)throw new Error('HTTP '+r.status);A().toast('Bulut bağlantısı başarılı ✓')}catch(e){alert('Bağlantı kurulamadı: '+e.message)}}
  async function pushCloud(silent=false){const c=V.cloudConfig();if(!c.url||!c.token){if(!silent)A().toast('Bulut bağlantısı yapılandırılmamış.');return false}try{const payload={app:'OZBILTAR',version:'7.4.0',updatedAt:new Date().toISOString(),device:c.device||'',deviceId:state().cloudMeta.deviceId,bundle:window.OZ_STORE.exportBundle(state())};const r=await fetch(cloudEndpoint(c,'/state'),{method:'PUT',headers:cloudHeaders(c),body:JSON.stringify(payload)});if(!r.ok)throw new Error('HTTP '+r.status);state().cloudMeta.lastPush=new Date().toISOString();state().cloudMeta.dirty=false;localStorage.setItem(window.OZ_CONFIG.storageKey,JSON.stringify(state()));if(!silent)A().toast('Buluta gönderildi ✓');renderCloud();return true}catch(e){if(!silent)alert('Buluta gönderilemedi: '+e.message);return false}}
  async function pullCloud(){const c=V.cloudConfig();if(!c.url||!c.token){A().toast('Bulut bağlantısı yapılandırılmamış.');return}if(!confirm('Buluttaki kayıt bu cihazdaki verinin yerine alınsın mı? Önce yerel yedek almak güvenlidir.'))return;try{const r=await fetch(cloudEndpoint(c,'/state'),{headers:cloudHeaders(c)});if(!r.ok)throw new Error('HTTP '+r.status);const x=await r.json();const bundle=x.bundle||x;const imported=window.OZ_STORE.importBundle(bundle);imported.cloudMeta ||= {};imported.cloudMeta.lastPull=new Date().toISOString();imported.cloudMeta.dirty=false;localStorage.setItem(window.OZ_CONFIG.storageKey,JSON.stringify(imported));A().replaceState(imported);A().toast('Bulut verisi alındı ✓');renderCloud()}catch(e){alert('Buluttan alınamadı: '+e.message)}}
  let autoTimer;function afterSave(){updateHeader();renderAnimalAttachments();const c=V.cloudConfig();if(c.auto&&c.url&&c.token){clearTimeout(autoTimer);autoTimer=setTimeout(()=>pushCloud(true),2500)}}

  function render(name){updateHeader();if(name==='users')renderUsers();if(name==='attachments')renderAttachments();if(name==='qr')renderQr();if(name==='herdPerformance')renderHerd();if(name==='cloud')renderCloud();if(name==='animalProfile')renderAnimalAttachments();}
  function init(){updateHeader();if($("newUserBtn"))$("newUserBtn").onclick=openNewUser;if($("switchUserBtn"))$("switchUserBtn").onclick=()=>{const s=state();A().openModal('Kullanıcı Değiştir',`<label class="wide">Kullanıcı<select name="uid">${s.users.filter(x=>x.active!==false).map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.role)}</option>`).join('')}</select></label>${A().formActions()}`,e=>{e.preventDefault();const id=new FormData(e.target).get('uid');A().closeModal();switchUser(id)});document.querySelector('.cancel-modal').onclick=A().closeModal};if($("newAttachmentBtn"))$("newAttachmentBtn").onclick=()=>openAttachmentModal();if($("animalAddAttachmentBtn"))$("animalAddAttachmentBtn").onclick=()=>{const s=state(),a=s.data.animals.find(x=>x.id===A().getCurrentAnimalId());openAttachmentModal({entityType:'animals',entityKey:a?.earTag||''})};if($("attachmentFilter"))$("attachmentFilter").onchange=renderAttachments;if($("qrAnimalSelect"))$("qrAnimalSelect").onchange=renderQr;if($("refreshQrBtn"))$("refreshQrBtn").onclick=renderQr;if($("openQrAnimalBtn"))$("openQrAnimalBtn").onclick=()=>A().openAnimalByEarTag($("qrAnimalSelect").value);if($("scanQrBtn"))$("scanQrBtn").onclick=()=>{if(window.AndroidBridge&&typeof AndroidBridge.scanQr==='function')AndroidBridge.scanQr();else alert('QR tarama Android APK içinde kamera ile çalışır.')};if($("saveCloudBtn"))$("saveCloudBtn").onclick=saveCloud;if($("cloudTestBtn"))$("cloudTestBtn").onclick=testCloud;if($("cloudPushBtn"))$("cloudPushBtn").onclick=()=>pushCloud(false);if($("cloudPullBtn"))$("cloudPullBtn").onclick=pullCloud;
    document.addEventListener('click',e=>{const b=e.target.closest('[data-quick-module],#newRecordBtn,.edit-record,.delete-record,#listAddBtn');if(!b)return;let mod=b.dataset.quickModule||A().getCurrentModule();if(b.id==='listAddBtn')mod=A().getSelectedListModule();if(!canWriteModule(mod)){e.preventDefault();e.stopImmediatePropagation();A().toast('Bu kayıt için yazma yetkin yok.')}},true);
    renderCurrent();
  }
  window.OZ_V74_UI={init,render,renderCurrent,canView,canWriteModule,afterSave,openAttachmentModal,onQrScanned,pushCloud};
  init();
})();