window.OZ_V73 = (()=>{
  const N=v=>Number.isFinite(Number(v))?Number(v):0;
  const sum=a=>a.reduce((s,v)=>s+N(v),0);
  const monthOf=s=>String(s||'').slice(0,7);
  const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(N(v));
  const num=(v,d=2)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(N(v));
  function unitKgCost(r){const p=N(r.unitPrice);if(!p)return null;switch(r.priceBasis){case 'TL/kg':return p;case 'TL/ton':return p/1000;case 'Çuval/Paket Toplamı':return N(r.packageKg)>0?p/N(r.packageKg):null;default:return null}}
  function milkPrice(state,month){const sales=(state.data.sales||[]).filter(r=>monthOf(r.date)===month&&r.type==='Süt'&&N(r.unitPrice)>0);if(sales.length){const q=sum(sales.map(r=>r.quantity));return q?sum(sales.map(r=>N(r.quantity)*N(r.unitPrice)))/q:sum(sales.map(r=>r.unitPrice))/sales.length}const income=sum((state.data.finance||[]).filter(r=>monthOf(r.date)===month&&r.type==='Gelir'&&r.category==='Süt Satışı').map(r=>r.amount));const liters=sum((state.data.milk||[]).filter(r=>monthOf(r.date)===month&&r.recordType==='Çiftlik Toplam').map(r=>r.liters));return liters?income/liters:0}
  function deriveCalendar(state){const out=[...(state.calendarEvents||[])].map(e=>({...e,source:e.source||'Özel'}));(state.data.reproduction||[]).forEach(r=>{if(r.expectedCalving)out.push({id:'repro-'+r.id,date:r.expectedCalving,title:`Doğum bekleniyor · Küpe ${r.earTag||'?'}`,type:'Doğum',source:'Üreme',priority:'Yüksek'})});(state.data.sales||[]).forEach(r=>{if(r.dueDate&&r.paymentStatus!=='Tahsil Edildi')out.push({id:'sale-'+r.id,date:r.dueDate,title:`Tahsilat · ${r.customer||r.product||'Satış'}`,type:'Tahsilat',source:'Satış',priority:'Yüksek'})});(state.data.purchase||[]).forEach(r=>{if(r.dueDate&&r.paymentStatus!=='Ödendi')out.push({id:'buy-'+r.id,date:r.dueDate,title:`Ödeme · ${r.supplier||r.item||'Satın alma'}`,type:'Ödeme',source:'Satın Alma',priority:'Orta'})});(state.data.maintenance||[]).forEach(r=>{if(r.lastService&&N(r.periodDays)>0){const d=new Date(r.lastService+'T00:00:00');d.setDate(d.getDate()+N(r.periodDays));out.push({id:'mnt-'+r.id,date:d.toISOString().slice(0,10),title:`Bakım · ${r.equipment||'Ekipman'}`,type:'Bakım',source:'Bakım',priority:'Orta'})}});(state.tasks||[]).forEach(r=>{if(r.dueDate&&r.status!=='Tamamlandı')out.push({id:'task-'+r.id,date:r.dueDate,title:`Görev · ${r.title}`,type:'Görev',source:'Görev',priority:r.priority||'Orta'})});return out.filter(e=>e.date).sort((a,b)=>a.date.localeCompare(b.date))}
  function animalProfitability(state,month){const price=milkPrice(state,month);const animals=(state.data.animals||[]).filter(a=>!['Satıldı','Öldü'].includes(a.status));const feedExp=sum((state.data.finance||[]).filter(r=>monthOf(r.date)===month&&r.type==='Gider'&&r.category==='Yem').map(r=>r.amount));const milking=Math.max(1,animals.filter(a=>a.status==='Sağmal').length);const feedPerMilking=feedExp/milking;return animals.map(a=>{const liters=sum((state.data.milk||[]).filter(r=>monthOf(r.date)===month&&r.recordType==='Hayvan Bazlı'&&String(r.earTag)===String(a.earTag)).map(r=>r.liters));const health=sum((state.data.health||[]).filter(r=>monthOf(r.date)===month&&String(r.earTag)===String(a.earTag)).map(r=>r.cost));const feed=a.status==='Sağmal'?feedPerMilking:0;const revenue=liters*price;const known=liters>0&&price>0;return {id:a.id,earTag:a.earTag,name:a.alias||a.name||'',status:a.status,liters,revenue,feed,health,profit:revenue-feed-health,known}}).sort((a,b)=>(b.known-a.known)||(b.profit-a.profit))}
  function rationAnalytics(state,month){return (state.data.feed||[]).filter(r=>monthOf(r.date)===month).map(r=>{const kgCost=unitKgCost(r);const total=kgCost===null?null:N(r.amountKg)*kgCost;const l=N(r.milkLiters);return {...r,kgCost,total,costPerLiter:total!==null&&l>0?total/l:null}}).sort((a,b)=>(b.date||'').localeCompare(a.date||''))}
  function currentAccounts(state){const map={};const get=(name,type)=>{const k=type+'|'+(name||'Bilinmeyen');return map[k]||(map[k]={key:k,name:name||'Bilinmeyen',type,receivable:0,payable:0,uncertain:false,items:0})};(state.data.sales||[]).forEach(r=>{if(r.paymentStatus!=='Tahsil Edildi'){const x=get(r.customer,'Müşteri');x.receivable+=N(r.quantity)*N(r.unitPrice);x.items++;if(r.paymentStatus==='Kısmi')x.uncertain=true}});(state.data.purchase||[]).forEach(r=>{if(r.paymentStatus!=='Ödendi'){const x=get(r.supplier,'Tedarikçi');x.payable+=N(r.quantity)*N(r.unitPrice);x.items++;if(r.paymentStatus==='Kısmi')x.uncertain=true}});return Object.values(map).sort((a,b)=>(b.receivable+b.payable)-(a.receivable+a.payable))}
  function cashBalance(state,acc){return N(acc.openingBalance)+sum((state.cashTransactions||[]).filter(t=>t.accountId===acc.id).map(t=>t.type==='Giriş'?N(t.amount):-N(t.amount)))}
  function monthlySnapshot(state,month){const fin=(state.data.finance||[]).filter(r=>monthOf(r.date)===month);const milk=(state.data.milk||[]).filter(r=>monthOf(r.date)===month&&r.recordType==='Çiftlik Toplam');const income=sum(fin.filter(r=>r.type==='Gelir').map(r=>r.amount));const expense=sum(fin.filter(r=>r.type==='Gider').map(r=>r.amount));const liters=sum(milk.map(r=>r.liters));const feed=sum(fin.filter(r=>r.type==='Gider'&&r.category==='Yem').map(r=>r.amount));const health=sum((state.data.health||[]).filter(r=>monthOf(r.date)===month).map(r=>r.cost));const ca=currentAccounts(state);return {month,createdAt:new Date().toISOString(),income,expense,net:income-expense,milkLiters:liters,avgDailyMilk:milk.length?liters/new Set(milk.map(r=>r.date)).size:0,feedExpense:feed,feedPerLiter:liters?feed/liters:0,healthCost:health,receivable:sum(ca.map(x=>x.receivable)),payable:sum(ca.map(x=>x.payable)),animals:(state.data.animals||[]).filter(a=>!['Satıldı','Öldü'].includes(a.status)).length,milking:(state.data.animals||[]).filter(a=>a.status==='Sağmal').length,openAlerts:0,recordCounts:Object.fromEntries(Object.entries(state.data).map(([k,v])=>[k,v.length]))}}
  function monthlyHtml(s,company={}){return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><style>@page{size:A4;margin:14mm}body{font:12px Arial;color:#243247}h1,h2{color:#122033}.head{border-bottom:3px solid #aa7743;padding-bottom:10px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.k{border:1px solid #dfe5ec;border-radius:8px;padding:9px}.k span{display:block;color:#6f7b8d;font-size:9px}.k b{font-size:16px;color:#122033}.sec{margin-top:16px}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #e3e8ee;text-align:left}</style></head><body><div class="head"><h1>${company.name||'ÖZBİLTAR'} · Aylık Yönetim Kapanışı</h1><div>${s.month} · ${company.location||''}</div></div><div class="sec grid">${[['Gelir',money(s.income)],['Gider',money(s.expense)],['Net',money(s.net)],['Süt',num(s.milkLiters,0)+' L'],['Yem',money(s.feedExpense)],['Yem TL/L',num(s.feedPerLiter,2)],['Alacak',money(s.receivable)],['Borç',money(s.payable)]].map(x=>`<div class="k"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="sec"><h2>Operasyon Özeti</h2><table><tr><th>Aktif Hayvan</th><td>${s.animals}</td><th>Sağmal</th><td>${s.milking}</td></tr><tr><th>Günlük Ort. Süt</th><td>${num(s.avgDailyMilk,1)} L</td><th>Sağlık Maliyeti</th><td>${money(s.healthCost)}</td></tr></table></div><div class="sec"><h2>Yönetim Notu</h2><p>Bu kapanış, kayıtlı verilerin dönemsel özetidir. Kısmi tahsilat/ödemelerde kalan tutar ayrıca girilmediyse cari bakiyeler yaklaşık olabilir.</p></div></body></html>`}
  return {monthOf,money,num,unitKgCost,milkPrice,deriveCalendar,animalProfitability,rationAnalytics,currentAccounts,cashBalance,monthlySnapshot,monthlyHtml};
})();